"""initial_schema

Revision ID: 4f632feceb91
Revises: 
Create Date: 2026-05-01 21:16:48.205020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f632feceb91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_lang', 'target_lang', 'source_hash', name='uq_translation_cache_lang_hash')
    )
    op.create_index('ix_translation_cache_lookup', 'translation_cache', ['source_lang', 'target_lang', 'source_hash'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'source_text', name='uq_cards_session_source_text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_index('ix_translation_cache_lookup', table_name='translation_cache')
    op.drop_table('translation_cache')
    op.drop_table('sessions')
    # ### end Alembic commands ###
