"""add source to sessions

Revision ID: 54c7d08eb378
Revises: 4f632feceb91
Create Date: 2026-05-13 23:20:34.322970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c7d08eb378'
down_revision: Union[str, Sequence[str], None] = '4f632feceb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_cache_lookup'), table_name='translation_cache')
    op.drop_table('translation_cache')
    op.add_column('sessions', sa.Column('source', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'source')
    op.create_table('translation_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_lang', sa.VARCHAR(length=16), nullable=False),
    sa.Column('target_lang', sa.VARCHAR(length=16), nullable=False),
    sa.Column('source_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('source_text', sa.TEXT(), nullable=False),
    sa.Column('translated_text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_lang', 'target_lang', 'source_hash', name=op.f('uq_translation_cache_lang_hash'))
    )
    op.create_index(op.f('ix_translation_cache_lookup'), 'translation_cache', ['source_lang', 'target_lang', 'source_hash'], unique=False)
    # ### end Alembic commands ###
